[package]
name = "fatorial_simples"
version = "0.1.0"
authors = ["kommander"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
